name: "Default Checks"

permissions:
  contents: read # for actions/checkout to fetch code
  checks: write # for merge gatekeeper to create checks
  statuses: write # for merge gatekeeper to create statuses

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check:
    uses: stuhlmuller/workflows/.github/workflows/default.yml@c607ccb40a968439f8ed6a5d848442556b519c64 # main
    with:
      checkov: false
      merge-checks-timeout: 300
