name: "Default Checks"

permissions:
  contents: read # for actions/checkout to fetch code
  checks: write # for merge gatekeeper to create checks
  statuses: write # for merge gatekeeper to create statuses

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check:
    uses: stuhlmuller/workflows/.github/workflows/default.yml@74b5e31d5e16c52d9ee79eaf44f580135065beda # main
    with:
      checkov: false
      merge-checks-timeout: 300
