name: "Default Checks"

permissions:
  contents: read # for actions/checkout to fetch code
  checks: write # for merge gatekeeper to create checks
  statuses: write # for merge gatekeeper to create statuses

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check:
    uses: stuhlmuller/workflows/.github/workflows/default.yml@d26688db16a42f70710c90ab307abcbfb618c63b # main
    with:
      checkov: false
      merge-checks-timeout: 300
